### Particle Image Function
### Version: 1.0.4
### Width: 80
### Height: 80
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^5 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.125 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.125 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.125 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.125 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.125 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.125 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^-3.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.25 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^-4 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^-3.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.375 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.5 ^0 ^4.75 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.625 ^0 ^4.75 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.25 ^0 ^4.75 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.125 ^0 ^4.75 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-4 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-3.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^-3.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.875 ^0 ^3.875 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^-3.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^-2.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^2.125 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.75 ^0 ^3 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.625 ^0 ^-1.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.625 ^0 ^-0.5 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.625 ^0 ^0.375 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.625 ^0 ^1.25 run function ui:common/particle/ss/downer/10032/point

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10032/damage

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged
