### Particle Image Function
### Version: 1.0.4
### Width: 80
### Height: 80
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^6.9090909 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6.9090909 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6.9090909 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6.9090909 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^5.6363636 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.3636364 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^-6 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.0909091 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^-6 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^1.8181818 ^0 ^6.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^-7.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^-6 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.5454545 ^0 ^6.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^-7.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^-6 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.7272727 ^0 ^6.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-6 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^-0.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^0.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2 ^0 ^6.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^-6 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^-2.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^1.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-3.2727273 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.5454545 ^0 ^-4.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.5454545 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.5454545 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.5454545 ^0 ^4.1818182 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.5454545 ^0 ^5.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.8181818 ^0 ^-3.4545455 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.8181818 ^0 ^2.9090909 run function ui:common/particle/ss/downer/10032/point

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10032/damage3

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged
