### Particle Image Function
### Version: 1.0.4
### Width: 80
### Height: 80
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^7.2727273 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^7.2727273 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^6 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^-4.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^4.7272727 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^-5.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^-4.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^3.4545455 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^2.1818182 ^0 ^6.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^0.9090909 ^0 ^6.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-0.3636364 ^0 ^6.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-1.6363636 ^0 ^6.9090909 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^-5.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^-4.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-2.9090909 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^-4.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-4.1818182 ^0 ^5.6363636 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^-4.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^-3.2727273 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^3.0909091 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-5.4545455 ^0 ^4.3636364 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-6.7272727 ^0 ^-2 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-6.7272727 ^0 ^-0.7272727 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-6.7272727 ^0 ^0.5454545 run function ui:common/particle/ss/downer/10032/point
execute positioned ^-6.7272727 ^0 ^1.8181818 run function ui:common/particle/ss/downer/10032/point

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10032/damage3

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged
