### Particle Image Function
### Version: 1.0.4
### Width: 40
### Height: 40
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^3.75 ^0 ^3.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^3.25 ^0 ^3.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^2.75 ^0 ^4.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^2.25 ^0 ^4.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^1.75 ^0 ^4.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^1.25 ^0 ^4.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^0.75 ^0 ^4.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^0.25 ^0 ^4.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-0.25 ^0 ^4.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-0.75 ^0 ^3.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.25 ^0 ^3.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.5 ^0 ^3 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2 ^0 ^2.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.25 ^0 ^2 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.75 ^0 ^1.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-3 ^0 ^0.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-3 ^0 ^1 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-3.25 ^0 ^0 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-3.5 ^0 ^-0.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-3.75 ^0 ^-1 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4 ^0 ^-2 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4 ^0 ^-1.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4.25 ^0 ^-3.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4.25 ^0 ^-3 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4.25 ^0 ^-2.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4.5 ^0 ^-5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4.5 ^0 ^-4.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-4.5 ^0 ^-4 run function ui:common/particle/ss/downer/10034/point

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10034/damage_k

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged