### Particle Image Function
### Version: 1.0.4
### Width: 40
### Height: 40
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute as @e[distance=..3,predicate=ui:load_unhurtable,tag=!ui_temp_team,tag=!ui_temp_damaged] run tag @s add ui_temp_damaged

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10034/damage_h_area
execute as @e[tag=ui_temp_damaged] facing entity @s feet run function ui:common/particle/ss/downer/10034/kb_h_area

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged