### Particle Image Function
### Version: 1.0.4
### Width: 40
### Height: 40
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^1.875 ^0 ^1.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^1.625 ^0 ^1.875 run function ui:common/particle/ss/downer/10034/point
execute positioned ^1.375 ^0 ^2.125 run function ui:common/particle/ss/downer/10034/point
execute positioned ^1.125 ^0 ^2.125 run function ui:common/particle/ss/downer/10034/point
execute positioned ^0.875 ^0 ^2.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^0.625 ^0 ^2.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^0.375 ^0 ^2.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^0.125 ^0 ^2.125 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-0.125 ^0 ^2.125 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-0.375 ^0 ^1.875 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-0.625 ^0 ^1.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-0.75 ^0 ^1.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1 ^0 ^1.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.125 ^0 ^1 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.375 ^0 ^0.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.5 ^0 ^0.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.5 ^0 ^0.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.625 ^0 ^0 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.75 ^0 ^-0.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-1.875 ^0 ^-0.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2 ^0 ^-1 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2 ^0 ^-0.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.125 ^0 ^-1.75 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.125 ^0 ^-1.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.125 ^0 ^-1.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.25 ^0 ^-2.5 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.25 ^0 ^-2.25 run function ui:common/particle/ss/downer/10034/point
execute positioned ^-2.25 ^0 ^-2 run function ui:common/particle/ss/downer/10034/point

execute as @e[tag=ui_temp_damaged] facing entity @s feet rotated ~ 0 run function ui:common/particle/ss/downer/10034/kb_o
execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10034/damage_o

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged
