### Particle Image Function
### Version: 1.0.4
### Width: 69
### Height: 25
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^1.5625 ^0 ^-0.5625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.5625 ^0 ^-0.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.5625 ^0 ^0.4375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^-2.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^-1.5625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^-1.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^-0.5625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^-0.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^0.4375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^0.9375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^1.4375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.0625 ^0 ^1.9375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.5625 ^0 ^-2.5625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.5625 ^0 ^-2.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.5625 ^0 ^1.9375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.5625 ^0 ^2.4375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.0625 ^0 ^-3.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.0625 ^0 ^2.9375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.4375 ^0 ^-3.5625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.4375 ^0 ^3.4375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.9375 ^0 ^-4.0625 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.9375 ^0 ^3.9375 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-1.4375 ^0 ^-4.3125 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-1.4375 ^0 ^4.1875 run function ui:common/particle/ss/downer/10033/point

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10033/damage

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged
