### Particle Image Function
### Version: 1.0.4
### Width: 35
### Height: 39
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged

execute positioned ^-0.03125 ^2.4375 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.34375 ^2.25 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^2.25 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.34375 ^2.25 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.71875 ^2.25 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^1.03125 ^2.25 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^1.9375 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.21875 ^1.9375 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^0.46875 ^1.9375 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^1.5625 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^1.1875 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^0.8125 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^0.4375 ^0 run function ui:common/particle/ss/downer/10033/point
execute positioned ^-0.03125 ^0.0625 ^0 run function ui:common/particle/ss/downer/10033/point

execute as @e[tag=ui_temp_damaged] at @s run function ui:common/particle/ss/downer/10033/damage

tag @e[tag=ui_temp_damaged] remove ui_temp_damaged
